### PR TITLE
Add favicon to header.

### PR DESCRIPTION
**Pull request by patdenice**

### CODE REVIEW

**Comment by modus75** [comment]
Sorry, but I did not put this on purpose as I don't see the interest to have this default icon and I have my own icon at the root of my site - all browsers request this root icon

**Comment by plegall** [comment]
All Piwigo themes have a favicon I think. modus75, why don't we have a default favicon on Modus as well and you can have a personal favicon with plugin Perso Favicon :-)

**Comment by plegall** [comment]
The default favicon is here to say "it's a Piwigo photo gallery", if we don't have it, we remove a part of the "brand" if you see what I mean. A bit like "powered by Piwigo". It is possible to customize/remove it, but it's better to have it by default in my opinion.

**Comment by plegall** [comment]
@modus75 Thank you ;-)

**Pull request merged**
